export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITITATE_LOGOUT = 'AUTH_INITITATE_LOGOUT'
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const POST_INITIAL_DATA = 'POST_INITIAL_DATA';
export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const POST_INITIAL_DATA_ON_SIGNUP = 'POST_INITIAL_DATA_ON_SIGNUP';

export const UPDATE_JOURNAL_DATA_TO_FIREBASE = 'UPDATE_JOURNAL_DATA_TO_FIREBASE';
export const POST_NEW_ENTRY_TO_FIREBASE = 'POST_NEW_ENTRY_TO_FIREBASE';